[config]
schemaVersion = "0.0.3"


[package]
namespace = "Wistiti"
name = "WrathOfOlympus"
versionNumber = "0.0.4"
description = "Adds a new Wrath boon for each Olympian."
websiteUrl = "https://github.com/WistitiPNF-404/WrathOfOlympus"
containsNsfwContent = false

[package.dependencies]
Hell2Modding-Hell2Modding = "1.0.83"
LuaENVY-ENVY = "1.2.0"
SGG_Modding-Chalk = "2.1.1"
SGG_Modding-ReLoad = "1.0.2"
SGG_Modding-SJSON = "1.0.0"
SGG_Modding-ModUtil = "4.0.1"
zannc-GodsAPI = "1.0.9"


[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./CHANGELOG.md"
target = "./CHANGELOG.md"

[[build.copy]]
source = "./LICENSE"
target = "./LICENSE"

[[build.copy]]
source = "./src"
target = "./plugins"

# Uncomment (remove the #) the three lines below if you have any files to copy to the plugins_data folder (like custom .pkg files)
# [[build.copy]]
# source = "./data"
# target = "./plugins_data"


[publish]
repository = "https://thunderstore.io"
communities = [ "hades-ii", ]

[publish.categories]
hades-ii = [ "mods", ]
